feat(JOML): migrate world generation
Terasology/Cities pull request #41
Opened 2020-12-13 21:08 UTC by jdrueckert

2020-12-25 21:36 UTC, skaldarnar commented on src/test/java/org/terasology/cities/bldg/DebugRasterTarget.java
> +        this.region = BlockRegions.createFromMinAndMax(new Vector3i(0, min, 0), new Vector3i(SIZE_X, max, SIZE_Z));
This no longer exists
```suggestion
        this.region = new BlockRegion(0, min, 0, SIZE_X, max, SIZE_Z);
```

2020-12-25 21:37 UTC, skaldarnar requested changes
Maybe this PR was not updated after the latest changes?

2020-12-25 21:37 UTC, skaldarnar commented on src/test/java/org/terasology/cities/bldg/DebugRasterTarget.java
> +        data.set(x, y - region.getMinY(), z, index);
```suggestion
        data.set(x, y - region.minY(), z, index);
```

2020-12-26 09:59 UTC, jdrueckert commented on src/test/java/org/terasology/cities/bldg/DebugRasterTarget.java
> +                return region.getMaxY() - region.getMinY() + 1;
```suggestion
                return region.maxY() - region.minY() + 1;
```

2020-12-26 11:41 UTC, skaldarnar submitted a review, later dismissed

2020-12-26 20:43 UTC, skaldarnar approved these changes

2020-12-26 20:46 UTC, merged