feat(JOML): get rid of `Region3i`
Terasology/Cities pull request #42
Opened 2020-12-31 15:36 UTC by jdrueckert

PR: https://github.com/Terasology/DynamicCities/pull/80

2020-12-31 17:15 UTC, pollend requested changes

2020-12-31 17:15 UTC, pollend commented on src/main/java/org/terasology/cities/deco/ColumnDecoration.java
> +        this.pos = basePos;
```suggestion
        this.pos.set(basePos);
```

2020-12-31 17:15 UTC, pollend commented on src/main/java/org/terasology/cities/deco/ColumnDecoration.java
> +    private final Vector3ic pos;
```suggestion
    private final Vector3ic pos = new Vector3i();
```

2020-12-31 17:15 UTC, pollend commented on src/main/java/org/terasology/cities/deco/ColumnDecoration.java
> +        this.pos = basePos;
write to a pre-declared one. makes it more immutable?

2020-12-31 17:15 UTC, pollend commented on src/main/java/org/terasology/cities/deco/SingleBlockDecoration.java
> +        this.pos = pos;
```suggestion
        this.pos.set(pos);
```

2020-12-31 17:15 UTC, pollend commented on src/main/java/org/terasology/cities/deco/SingleBlockDecoration.java
> +    private final Vector3ic pos;
```suggestion
    private final Vector3ic pos = new Vector3i();
```

2020-12-31 18:46 UTC, pollend approved these changes, later dismissed

2021-01-01 23:49 UTC, pollend approved these changes

2021-01-03 11:16 UTC, skaldarnar approved these changes

2021-01-03 11:22 UTC, merged